// Code generated by Fern. DO NOT EDIT.

package instance

import (
	context "context"

	sdk "github.com/Acksell/opencode-go-sdk/sdk"
	core "github.com/Acksell/opencode-go-sdk/sdk/core"
	internal "github.com/Acksell/opencode-go-sdk/sdk/internal"
	option "github.com/Acksell/opencode-go-sdk/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Clean up and dispose the current OpenCode instance, releasing all resources.
func (c *Client) Dispose(
	ctx context.Context,
	request *sdk.InstanceDisposeRequest,
	opts ...option.RequestOption,
) (bool, error) {
	response, err := c.WithRawResponse.Dispose(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return false, err
	}
	return response.Body, nil
}

// Get a list of all available AI agents in the OpenCode system.
func (c *Client) AppAgents(
	ctx context.Context,
	request *sdk.AppAgentsRequest,
	opts ...option.RequestOption,
) ([]*sdk.Agent, error) {
	response, err := c.WithRawResponse.AppAgents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
