// Code generated by Fern. DO NOT EDIT.

package session_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	sdk "github.com/Acksell/opencode-go-sdk/sdk"
	client "github.com/Acksell/opencode-go-sdk/sdk/client"
	option "github.com/Acksell/opencode-go-sdk/sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSessionListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionListRequest{}
	_, invocationErr := client.Session.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionListWithWireMock", "GET", "/session", nil, 1)
}

func TestSessionCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionCreateRequest{}
	_, invocationErr := client.Session.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionCreateWithWireMock", "POST", "/session", nil, 1)
}

func TestSessionStatusWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionStatusRequest{}
	_, invocationErr := client.Session.Status(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionStatusWithWireMock", "GET", "/session/status", nil, 1)
}

func TestSessionGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionGetRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionGetWithWireMock", "GET", "/session/sessionID", nil, 1)
}

func TestSessionDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionDeleteRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionDeleteWithWireMock", "DELETE", "/session/sessionID", nil, 1)
}

func TestSessionUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionUpdateRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionUpdateWithWireMock", "PATCH", "/session/sessionID", nil, 1)
}

func TestSessionChildrenWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionChildrenRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Children(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionChildrenWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionChildrenWithWireMock", "GET", "/session/sessionID/children", nil, 1)
}

func TestSessionTodoWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionTodoRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Todo(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionTodoWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionTodoWithWireMock", "GET", "/session/sessionID/todo", nil, 1)
}

func TestSessionDiffWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionDiffRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Diff(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionDiffWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionDiffWithWireMock", "GET", "/session/sessionID/diff", nil, 1)
}

func TestSessionMessagesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionMessagesRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Messages(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionMessagesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionMessagesWithWireMock", "GET", "/session/sessionID/message", nil, 1)
}

func TestSessionPromptWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionPromptRequest{
		SessionID: "sessionID",
		Parts: []*sdk.SessionPromptRequestPartsItem{
			&sdk.SessionPromptRequestPartsItem{
				Text: &sdk.TextPartInput{
					Text: "text",
				},
			},
		},
	}
	_, invocationErr := client.Session.Prompt(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionPromptWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionPromptWithWireMock", "POST", "/session/sessionID/message", nil, 1)
}

func TestSessionMessageWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionMessageRequest{
		SessionID: "sessionID",
		MessageID: "messageID",
	}
	_, invocationErr := client.Session.Message(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionMessageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionMessageWithWireMock", "GET", "/session/sessionID/message/messageID", nil, 1)
}

func TestSessionDeletemessageWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionDeleteMessageRequest{
		SessionID: "sessionID",
		MessageID: "messageID",
	}
	_, invocationErr := client.Session.Deletemessage(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionDeletemessageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionDeletemessageWithWireMock", "DELETE", "/session/sessionID/message/messageID", nil, 1)
}

func TestSessionForkWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionForkRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Fork(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionForkWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionForkWithWireMock", "POST", "/session/sessionID/fork", nil, 1)
}

func TestSessionAbortWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionAbortRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Abort(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionAbortWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionAbortWithWireMock", "POST", "/session/sessionID/abort", nil, 1)
}

func TestSessionInitWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionInitRequest{
		SessionID:  "sessionID",
		ModelID:    "modelID",
		ProviderID: "providerID",
		MessageID:  "messageID",
	}
	_, invocationErr := client.Session.Init(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionInitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionInitWithWireMock", "POST", "/session/sessionID/init", nil, 1)
}

func TestSessionShareWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionShareRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Share(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionShareWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionShareWithWireMock", "POST", "/session/sessionID/share", nil, 1)
}

func TestSessionUnshareWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionUnshareRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Unshare(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionUnshareWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionUnshareWithWireMock", "DELETE", "/session/sessionID/share", nil, 1)
}

func TestSessionSummarizeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionSummarizeRequest{
		SessionID:  "sessionID",
		ProviderID: "providerID",
		ModelID:    "modelID",
	}
	_, invocationErr := client.Session.Summarize(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionSummarizeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionSummarizeWithWireMock", "POST", "/session/sessionID/summarize", nil, 1)
}

func TestSessionPromptAsyncWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionPromptAsyncRequest{
		SessionID: "sessionID",
		Parts: []*sdk.SessionPromptAsyncRequestPartsItem{
			&sdk.SessionPromptAsyncRequestPartsItem{
				Text: &sdk.TextPartInput{
					Text: "text",
				},
			},
		},
	}
	invocationErr := client.Session.PromptAsync(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionPromptAsyncWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionPromptAsyncWithWireMock", "POST", "/session/sessionID/prompt_async", nil, 1)
}

func TestSessionCommandWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionCommandRequest{
		SessionID: "sessionID",
		Arguments: "arguments",
		Command:   "command",
	}
	_, invocationErr := client.Session.Command(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionCommandWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionCommandWithWireMock", "POST", "/session/sessionID/command", nil, 1)
}

func TestSessionShellWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionShellRequest{
		SessionID: "sessionID",
		Agent:     "agent",
		Command:   "command",
	}
	_, invocationErr := client.Session.Shell(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionShellWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionShellWithWireMock", "POST", "/session/sessionID/shell", nil, 1)
}

func TestSessionRevertWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionRevertRequest{
		SessionID: "sessionID",
		MessageID: "messageID",
	}
	_, invocationErr := client.Session.Revert(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionRevertWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionRevertWithWireMock", "POST", "/session/sessionID/revert", nil, 1)
}

func TestSessionUnrevertWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SessionUnrevertRequest{
		SessionID: "sessionID",
	}
	_, invocationErr := client.Session.Unrevert(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionUnrevertWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionUnrevertWithWireMock", "POST", "/session/sessionID/unrevert", nil, 1)
}

func TestSessionPermissionRespondWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.PermissionRespondRequest{
		SessionID:    "sessionID",
		PermissionID: "permissionID",
		Response:     sdk.PermissionRespondRequestResponseOnce,
	}
	_, invocationErr := client.Session.PermissionRespond(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionPermissionRespondWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionPermissionRespondWithWireMock", "POST", "/session/sessionID/permissions/permissionID", nil, 1)
}

func TestSessionPartDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.PartDeleteRequest{
		SessionID: "sessionID",
		MessageID: "messageID",
		PartID:    "partID",
	}
	_, invocationErr := client.Session.PartDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionPartDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionPartDeleteWithWireMock", "DELETE", "/session/sessionID/message/messageID/part/partID", nil, 1)
}

func TestSessionPartUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.PartUpdateRequest{
		SessionID: "sessionID",
		MessageID: "messageID",
		PartID:    "partID",
		Body: &sdk.Part{
			Text: &sdk.TextPart{
				ID:        "id",
				SessionID: "sessionID",
				MessageID: "messageID",
				Text:      "text",
			},
		},
	}
	_, invocationErr := client.Session.PartUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSessionPartUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSessionPartUpdateWithWireMock", "PATCH", "/session/sessionID/message/messageID/part/partID", nil, 1)
}
