// Code generated by Fern. DO NOT EDIT.

package provider

import (
	context "context"

	sdk "github.com/Acksell/opencode-go-sdk/sdk"
	core "github.com/Acksell/opencode-go-sdk/sdk/core"
	internal "github.com/Acksell/opencode-go-sdk/sdk/internal"
	option "github.com/Acksell/opencode-go-sdk/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get a list of all available AI providers, including both available and connected ones.
func (c *Client) List(
	ctx context.Context,
	request *sdk.ProviderListRequest,
	opts ...option.RequestOption,
) (*sdk.ProviderListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve available authentication methods for all AI providers.
func (c *Client) Auth(
	ctx context.Context,
	request *sdk.ProviderAuthRequest,
	opts ...option.RequestOption,
) (map[string][]*sdk.ProviderAuthMethod, error) {
	response, err := c.WithRawResponse.Auth(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Start the OAuth authorization flow for a provider.
func (c *Client) OauthAuthorize(
	ctx context.Context,
	request *sdk.ProviderOauthAuthorizeRequest,
	opts ...option.RequestOption,
) (*sdk.ProviderAuthAuthorization, error) {
	response, err := c.WithRawResponse.OauthAuthorize(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Handle the OAuth callback from a provider after user authorization.
func (c *Client) OauthCallback(
	ctx context.Context,
	request *sdk.ProviderOauthCallbackRequest,
	opts ...option.RequestOption,
) (bool, error) {
	response, err := c.WithRawResponse.OauthCallback(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return false, err
	}
	return response.Body, nil
}
