// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/acksell/opencode-go-sdk/sdk/internal"
	big "math/big"
)

var (
	authRemoveRequestFieldProviderID = big.NewInt(1 << 0)
)

type AuthRemoveRequest struct {
	ProviderID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AuthRemoveRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetProviderID sets the ProviderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRemoveRequest) SetProviderID(providerID string) {
	a.ProviderID = providerID
	a.require(authRemoveRequestFieldProviderID)
}

var (
	authSetRequestFieldProviderID = big.NewInt(1 << 0)
)

type AuthSetRequest struct {
	ProviderID string `json:"-" url:"-"`
	Body       *Auth  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AuthSetRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetProviderID sets the ProviderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthSetRequest) SetProviderID(providerID string) {
	a.ProviderID = providerID
	a.require(authSetRequestFieldProviderID)
}

func (a *AuthSetRequest) UnmarshalJSON(data []byte) error {
	body := new(Auth)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	a.Body = body
	return nil
}

func (a *AuthSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.Body)
}

var (
	aPIAuthFieldKey      = big.NewInt(1 << 0)
	aPIAuthFieldMetadata = big.NewInt(1 << 1)
)

type APIAuth struct {
	Key      string            `json:"key" url:"key"`
	Metadata map[string]string `json:"metadata,omitempty" url:"metadata,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIAuth) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *APIAuth) GetMetadata() map[string]string {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *APIAuth) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIAuth) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIAuth) SetKey(key string) {
	a.Key = key
	a.require(aPIAuthFieldKey)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIAuth) SetMetadata(metadata map[string]string) {
	a.Metadata = metadata
	a.require(aPIAuthFieldMetadata)
}

func (a *APIAuth) UnmarshalJSON(data []byte) error {
	type unmarshaler APIAuth
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = APIAuth(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIAuth) MarshalJSON() ([]byte, error) {
	type embed APIAuth
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIAuth) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type Auth struct {
	Type      string
	Oauth     *OAuth
	API       *APIAuth
	Wellknown *WellKnownAuth
}

func (a *Auth) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *Auth) GetOauth() *OAuth {
	if a == nil {
		return nil
	}
	return a.Oauth
}

func (a *Auth) GetAPI() *APIAuth {
	if a == nil {
		return nil
	}
	return a.API
}

func (a *Auth) GetWellknown() *WellKnownAuth {
	if a == nil {
		return nil
	}
	return a.Wellknown
}

func (a *Auth) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	a.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", a)
	}
	switch unmarshaler.Type {
	case "oauth":
		value := new(OAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Oauth = value
	case "api":
		value := new(APIAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.API = value
	case "wellknown":
		value := new(WellKnownAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Wellknown = value
	}
	return nil
}

func (a Auth) MarshalJSON() ([]byte, error) {
	if err := a.validate(); err != nil {
		return nil, err
	}
	if a.Oauth != nil {
		return internal.MarshalJSONWithExtraProperty(a.Oauth, "type", "oauth")
	}
	if a.API != nil {
		return internal.MarshalJSONWithExtraProperty(a.API, "type", "api")
	}
	if a.Wellknown != nil {
		return internal.MarshalJSONWithExtraProperty(a.Wellknown, "type", "wellknown")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", a)
}

type AuthVisitor interface {
	VisitOauth(*OAuth) error
	VisitAPI(*APIAuth) error
	VisitWellknown(*WellKnownAuth) error
}

func (a *Auth) Accept(visitor AuthVisitor) error {
	if a.Oauth != nil {
		return visitor.VisitOauth(a.Oauth)
	}
	if a.API != nil {
		return visitor.VisitAPI(a.API)
	}
	if a.Wellknown != nil {
		return visitor.VisitWellknown(a.Wellknown)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", a)
}

func (a *Auth) validate() error {
	if a == nil {
		return fmt.Errorf("type %T is nil", a)
	}
	var fields []string
	if a.Oauth != nil {
		fields = append(fields, "oauth")
	}
	if a.API != nil {
		fields = append(fields, "api")
	}
	if a.Wellknown != nil {
		fields = append(fields, "wellknown")
	}
	if len(fields) == 0 {
		if a.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", a, a.Type)
		}
		return fmt.Errorf("type %T is empty", a)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", a, fields)
	}
	if a.Type != "" {
		field := fields[0]
		if a.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				a,
				a.Type,
				a,
			)
		}
	}
	return nil
}

var (
	oAuthFieldRefresh       = big.NewInt(1 << 0)
	oAuthFieldAccess        = big.NewInt(1 << 1)
	oAuthFieldExpires       = big.NewInt(1 << 2)
	oAuthFieldAccountID     = big.NewInt(1 << 3)
	oAuthFieldEnterpriseURL = big.NewInt(1 << 4)
)

type OAuth struct {
	Refresh       string  `json:"refresh" url:"refresh"`
	Access        string  `json:"access" url:"access"`
	Expires       int     `json:"expires" url:"expires"`
	AccountID     *string `json:"accountId,omitempty" url:"accountId,omitempty"`
	EnterpriseURL *string `json:"enterpriseUrl,omitempty" url:"enterpriseUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OAuth) GetRefresh() string {
	if o == nil {
		return ""
	}
	return o.Refresh
}

func (o *OAuth) GetAccess() string {
	if o == nil {
		return ""
	}
	return o.Access
}

func (o *OAuth) GetExpires() int {
	if o == nil {
		return 0
	}
	return o.Expires
}

func (o *OAuth) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

func (o *OAuth) GetEnterpriseURL() *string {
	if o == nil {
		return nil
	}
	return o.EnterpriseURL
}

func (o *OAuth) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OAuth) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetRefresh sets the Refresh field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OAuth) SetRefresh(refresh string) {
	o.Refresh = refresh
	o.require(oAuthFieldRefresh)
}

// SetAccess sets the Access field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OAuth) SetAccess(access string) {
	o.Access = access
	o.require(oAuthFieldAccess)
}

// SetExpires sets the Expires field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OAuth) SetExpires(expires int) {
	o.Expires = expires
	o.require(oAuthFieldExpires)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OAuth) SetAccountID(accountID *string) {
	o.AccountID = accountID
	o.require(oAuthFieldAccountID)
}

// SetEnterpriseURL sets the EnterpriseURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OAuth) SetEnterpriseURL(enterpriseURL *string) {
	o.EnterpriseURL = enterpriseURL
	o.require(oAuthFieldEnterpriseURL)
}

func (o *OAuth) UnmarshalJSON(data []byte) error {
	type unmarshaler OAuth
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OAuth(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OAuth) MarshalJSON() ([]byte, error) {
	type embed OAuth
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OAuth) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	wellKnownAuthFieldKey   = big.NewInt(1 << 0)
	wellKnownAuthFieldToken = big.NewInt(1 << 1)
)

type WellKnownAuth struct {
	Key   string `json:"key" url:"key"`
	Token string `json:"token" url:"token"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WellKnownAuth) GetKey() string {
	if w == nil {
		return ""
	}
	return w.Key
}

func (w *WellKnownAuth) GetToken() string {
	if w == nil {
		return ""
	}
	return w.Token
}

func (w *WellKnownAuth) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WellKnownAuth) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WellKnownAuth) SetKey(key string) {
	w.Key = key
	w.require(wellKnownAuthFieldKey)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WellKnownAuth) SetToken(token string) {
	w.Token = token
	w.require(wellKnownAuthFieldToken)
}

func (w *WellKnownAuth) UnmarshalJSON(data []byte) error {
	type unmarshaler WellKnownAuth
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WellKnownAuth(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WellKnownAuth) MarshalJSON() ([]byte, error) {
	type embed WellKnownAuth
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WellKnownAuth) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}
