// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersAppAgentsRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &AppAgentsRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &AppAgentsRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAppAgentsRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AppAgentsRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AppAgentsRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersInstanceDisposeRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &InstanceDisposeRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &InstanceDisposeRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitInstanceDisposeRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstanceDisposeRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstanceDisposeRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAgent(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDescription", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueDescription *string
		obj.SetDescription(fernTestValueDescription)
		assert.Equal(t, fernTestValueDescription, obj.Description)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMode", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueMode AgentMode
		obj.SetMode(fernTestValueMode)
		assert.Equal(t, fernTestValueMode, obj.Mode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNative", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueNative *bool
		obj.SetNative(fernTestValueNative)
		assert.Equal(t, fernTestValueNative, obj.Native)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHidden", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueHidden *bool
		obj.SetHidden(fernTestValueHidden)
		assert.Equal(t, fernTestValueHidden, obj.Hidden)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTopP", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueTopP *float64
		obj.SetTopP(fernTestValueTopP)
		assert.Equal(t, fernTestValueTopP, obj.TopP)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTemperature", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueTemperature *float64
		obj.SetTemperature(fernTestValueTemperature)
		assert.Equal(t, fernTestValueTemperature, obj.Temperature)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetColor", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueColor *string
		obj.SetColor(fernTestValueColor)
		assert.Equal(t, fernTestValueColor, obj.Color)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPermission", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValuePermission PermissionRuleset
		obj.SetPermission(fernTestValuePermission)
		assert.Equal(t, fernTestValuePermission, obj.Permission)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModel", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueModel *AgentModel
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVariant", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueVariant *string
		obj.SetVariant(fernTestValueVariant)
		assert.Equal(t, fernTestValueVariant, obj.Variant)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrompt", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValuePrompt *string
		obj.SetPrompt(fernTestValuePrompt)
		assert.Equal(t, fernTestValuePrompt, obj.Prompt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOptions", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueOptions map[string]any
		obj.SetOptions(fernTestValueOptions)
		assert.Equal(t, fernTestValueOptions, obj.Options)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSteps", func(t *testing.T) {
		obj := &Agent{}
		var fernTestValueSteps *float64
		obj.SetSteps(fernTestValueSteps)
		assert.Equal(t, fernTestValueSteps, obj.Steps)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAgent(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetDescription", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *string
		obj.Description = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDescription(), "getter should return the property value")
	})

	t.Run("GetDescription_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Description = nil

		// Act & Assert
		assert.Nil(t, obj.GetDescription(), "getter should return nil when property is nil")
	})

	t.Run("GetDescription_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDescription() // Should return zero value
	})

	t.Run("GetMode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected AgentMode
		obj.Mode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMode(), "getter should return the property value")
	})

	t.Run("GetMode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMode() // Should return zero value
	})

	t.Run("GetNative", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *bool
		obj.Native = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNative(), "getter should return the property value")
	})

	t.Run("GetNative_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Native = nil

		// Act & Assert
		assert.Nil(t, obj.GetNative(), "getter should return nil when property is nil")
	})

	t.Run("GetNative_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNative() // Should return zero value
	})

	t.Run("GetHidden", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *bool
		obj.Hidden = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHidden(), "getter should return the property value")
	})

	t.Run("GetHidden_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Hidden = nil

		// Act & Assert
		assert.Nil(t, obj.GetHidden(), "getter should return nil when property is nil")
	})

	t.Run("GetHidden_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHidden() // Should return zero value
	})

	t.Run("GetTopP", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *float64
		obj.TopP = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTopP(), "getter should return the property value")
	})

	t.Run("GetTopP_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.TopP = nil

		// Act & Assert
		assert.Nil(t, obj.GetTopP(), "getter should return nil when property is nil")
	})

	t.Run("GetTopP_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTopP() // Should return zero value
	})

	t.Run("GetTemperature", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *float64
		obj.Temperature = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTemperature(), "getter should return the property value")
	})

	t.Run("GetTemperature_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Temperature = nil

		// Act & Assert
		assert.Nil(t, obj.GetTemperature(), "getter should return nil when property is nil")
	})

	t.Run("GetTemperature_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTemperature() // Should return zero value
	})

	t.Run("GetColor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *string
		obj.Color = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetColor(), "getter should return the property value")
	})

	t.Run("GetColor_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Color = nil

		// Act & Assert
		assert.Nil(t, obj.GetColor(), "getter should return nil when property is nil")
	})

	t.Run("GetColor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetColor() // Should return zero value
	})

	t.Run("GetPermission", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected PermissionRuleset
		obj.Permission = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPermission(), "getter should return the property value")
	})

	t.Run("GetPermission_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPermission() // Should return zero value
	})

	t.Run("GetModel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *AgentModel
		obj.Model = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModel(), "getter should return the property value")
	})

	t.Run("GetModel_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Model = nil

		// Act & Assert
		assert.Nil(t, obj.GetModel(), "getter should return nil when property is nil")
	})

	t.Run("GetModel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModel() // Should return zero value
	})

	t.Run("GetVariant", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *string
		obj.Variant = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVariant(), "getter should return the property value")
	})

	t.Run("GetVariant_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Variant = nil

		// Act & Assert
		assert.Nil(t, obj.GetVariant(), "getter should return nil when property is nil")
	})

	t.Run("GetVariant_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVariant() // Should return zero value
	})

	t.Run("GetPrompt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *string
		obj.Prompt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPrompt(), "getter should return the property value")
	})

	t.Run("GetPrompt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Prompt = nil

		// Act & Assert
		assert.Nil(t, obj.GetPrompt(), "getter should return nil when property is nil")
	})

	t.Run("GetPrompt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPrompt() // Should return zero value
	})

	t.Run("GetOptions", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected map[string]any
		obj.Options = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOptions(), "getter should return the property value")
	})

	t.Run("GetOptions_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Options = nil

		// Act & Assert
		assert.Nil(t, obj.GetOptions(), "getter should return nil when property is nil")
	})

	t.Run("GetOptions_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOptions() // Should return zero value
	})

	t.Run("GetSteps", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var expected *float64
		obj.Steps = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSteps(), "getter should return the property value")
	})

	t.Run("GetSteps_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		obj.Steps = nil

		// Act & Assert
		assert.Nil(t, obj.GetSteps(), "getter should return nil when property is nil")
	})

	t.Run("GetSteps_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSteps() // Should return zero value
	})

}

func TestSettersMarkExplicitAgent(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDescription_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueDescription *string

		// Act
		obj.SetDescription(fernTestValueDescription)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueMode AgentMode

		// Act
		obj.SetMode(fernTestValueMode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNative_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueNative *bool

		// Act
		obj.SetNative(fernTestValueNative)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHidden_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueHidden *bool

		// Act
		obj.SetHidden(fernTestValueHidden)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTopP_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueTopP *float64

		// Act
		obj.SetTopP(fernTestValueTopP)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTemperature_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueTemperature *float64

		// Act
		obj.SetTemperature(fernTestValueTemperature)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetColor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueColor *string

		// Act
		obj.SetColor(fernTestValueColor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPermission_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValuePermission PermissionRuleset

		// Act
		obj.SetPermission(fernTestValuePermission)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueModel *AgentModel

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVariant_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueVariant *string

		// Act
		obj.SetVariant(fernTestValueVariant)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrompt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValuePrompt *string

		// Act
		obj.SetPrompt(fernTestValuePrompt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOptions_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueOptions map[string]any

		// Act
		obj.SetOptions(fernTestValueOptions)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSteps_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}
		var fernTestValueSteps *float64

		// Act
		obj.SetSteps(fernTestValueSteps)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAgentModel(t *testing.T) {
	t.Run("SetModelID", func(t *testing.T) {
		obj := &AgentModel{}
		var fernTestValueModelID string
		obj.SetModelID(fernTestValueModelID)
		assert.Equal(t, fernTestValueModelID, obj.ModelID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProviderID", func(t *testing.T) {
		obj := &AgentModel{}
		var fernTestValueProviderID string
		obj.SetProviderID(fernTestValueProviderID)
		assert.Equal(t, fernTestValueProviderID, obj.ProviderID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAgentModel(t *testing.T) {
	t.Run("GetModelID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AgentModel{}
		var expected string
		obj.ModelID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModelID(), "getter should return the property value")
	})

	t.Run("GetModelID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AgentModel
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModelID() // Should return zero value
	})

	t.Run("GetProviderID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AgentModel{}
		var expected string
		obj.ProviderID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProviderID(), "getter should return the property value")
	})

	t.Run("GetProviderID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AgentModel
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProviderID() // Should return zero value
	})

}

func TestSettersMarkExplicitAgentModel(t *testing.T) {
	t.Run("SetModelID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AgentModel{}
		var fernTestValueModelID string

		// Act
		obj.SetModelID(fernTestValueModelID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProviderID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AgentModel{}
		var fernTestValueProviderID string

		// Act
		obj.SetProviderID(fernTestValueProviderID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingAgent(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Agent{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Agent
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Agent
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Agent
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingAgentModel(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AgentModel{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AgentModel
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AgentModel
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AgentModel
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringAgent(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Agent{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringAgentModel(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AgentModel{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AgentModel
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumAgentMode(t *testing.T) {
	t.Run("NewFromString_subagent", func(t *testing.T) {
		t.Parallel()
		val, err := NewAgentModeFromString("subagent")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AgentMode("subagent"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_primary", func(t *testing.T) {
		t.Parallel()
		val, err := NewAgentModeFromString("primary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AgentMode("primary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_all", func(t *testing.T) {
		t.Parallel()
		val, err := NewAgentModeFromString("all")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AgentMode("all"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewAgentModeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewAgentModeFromString("subagent")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesAgent(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Agent{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Agent
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesAgentModel(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AgentModel{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AgentModel
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
