// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Acksell/opencode-go-sdk/sdk/internal"
	big "math/big"
)

var (
	appAgentsRequestFieldDirectory = big.NewInt(1 << 0)
	appAgentsRequestFieldWorkspace = big.NewInt(1 << 1)
)

type AppAgentsRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AppAgentsRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AppAgentsRequest) SetDirectory(directory *string) {
	a.Directory = directory
	a.require(appAgentsRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AppAgentsRequest) SetWorkspace(workspace *string) {
	a.Workspace = workspace
	a.require(appAgentsRequestFieldWorkspace)
}

var (
	instanceDisposeRequestFieldDirectory = big.NewInt(1 << 0)
	instanceDisposeRequestFieldWorkspace = big.NewInt(1 << 1)
)

type InstanceDisposeRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstanceDisposeRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstanceDisposeRequest) SetDirectory(directory *string) {
	i.Directory = directory
	i.require(instanceDisposeRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstanceDisposeRequest) SetWorkspace(workspace *string) {
	i.Workspace = workspace
	i.require(instanceDisposeRequestFieldWorkspace)
}

var (
	agentFieldName        = big.NewInt(1 << 0)
	agentFieldDescription = big.NewInt(1 << 1)
	agentFieldMode        = big.NewInt(1 << 2)
	agentFieldNative      = big.NewInt(1 << 3)
	agentFieldHidden      = big.NewInt(1 << 4)
	agentFieldTopP        = big.NewInt(1 << 5)
	agentFieldTemperature = big.NewInt(1 << 6)
	agentFieldColor       = big.NewInt(1 << 7)
	agentFieldPermission  = big.NewInt(1 << 8)
	agentFieldModel       = big.NewInt(1 << 9)
	agentFieldVariant     = big.NewInt(1 << 10)
	agentFieldPrompt      = big.NewInt(1 << 11)
	agentFieldOptions     = big.NewInt(1 << 12)
	agentFieldSteps       = big.NewInt(1 << 13)
)

type Agent struct {
	Name        string            `json:"name" url:"name"`
	Description *string           `json:"description,omitempty" url:"description,omitempty"`
	Mode        AgentMode         `json:"mode" url:"mode"`
	Native      *bool             `json:"native,omitempty" url:"native,omitempty"`
	Hidden      *bool             `json:"hidden,omitempty" url:"hidden,omitempty"`
	TopP        *float64          `json:"topP,omitempty" url:"topP,omitempty"`
	Temperature *float64          `json:"temperature,omitempty" url:"temperature,omitempty"`
	Color       *string           `json:"color,omitempty" url:"color,omitempty"`
	Permission  PermissionRuleset `json:"permission" url:"permission"`
	Model       *AgentModel       `json:"model,omitempty" url:"model,omitempty"`
	Variant     *string           `json:"variant,omitempty" url:"variant,omitempty"`
	Prompt      *string           `json:"prompt,omitempty" url:"prompt,omitempty"`
	Options     map[string]any    `json:"options" url:"options"`
	Steps       *float64          `json:"steps,omitempty" url:"steps,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *Agent) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *Agent) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *Agent) GetMode() AgentMode {
	if a == nil {
		return ""
	}
	return a.Mode
}

func (a *Agent) GetNative() *bool {
	if a == nil {
		return nil
	}
	return a.Native
}

func (a *Agent) GetHidden() *bool {
	if a == nil {
		return nil
	}
	return a.Hidden
}

func (a *Agent) GetTopP() *float64 {
	if a == nil {
		return nil
	}
	return a.TopP
}

func (a *Agent) GetTemperature() *float64 {
	if a == nil {
		return nil
	}
	return a.Temperature
}

func (a *Agent) GetColor() *string {
	if a == nil {
		return nil
	}
	return a.Color
}

func (a *Agent) GetPermission() PermissionRuleset {
	if a == nil {
		return nil
	}
	return a.Permission
}

func (a *Agent) GetModel() *AgentModel {
	if a == nil {
		return nil
	}
	return a.Model
}

func (a *Agent) GetVariant() *string {
	if a == nil {
		return nil
	}
	return a.Variant
}

func (a *Agent) GetPrompt() *string {
	if a == nil {
		return nil
	}
	return a.Prompt
}

func (a *Agent) GetOptions() map[string]any {
	if a == nil {
		return nil
	}
	return a.Options
}

func (a *Agent) GetSteps() *float64 {
	if a == nil {
		return nil
	}
	return a.Steps
}

func (a *Agent) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *Agent) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetName(name string) {
	a.Name = name
	a.require(agentFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetDescription(description *string) {
	a.Description = description
	a.require(agentFieldDescription)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetMode(mode AgentMode) {
	a.Mode = mode
	a.require(agentFieldMode)
}

// SetNative sets the Native field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetNative(native *bool) {
	a.Native = native
	a.require(agentFieldNative)
}

// SetHidden sets the Hidden field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetHidden(hidden *bool) {
	a.Hidden = hidden
	a.require(agentFieldHidden)
}

// SetTopP sets the TopP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetTopP(topP *float64) {
	a.TopP = topP
	a.require(agentFieldTopP)
}

// SetTemperature sets the Temperature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetTemperature(temperature *float64) {
	a.Temperature = temperature
	a.require(agentFieldTemperature)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetColor(color *string) {
	a.Color = color
	a.require(agentFieldColor)
}

// SetPermission sets the Permission field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetPermission(permission PermissionRuleset) {
	a.Permission = permission
	a.require(agentFieldPermission)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetModel(model *AgentModel) {
	a.Model = model
	a.require(agentFieldModel)
}

// SetVariant sets the Variant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetVariant(variant *string) {
	a.Variant = variant
	a.require(agentFieldVariant)
}

// SetPrompt sets the Prompt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetPrompt(prompt *string) {
	a.Prompt = prompt
	a.require(agentFieldPrompt)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetOptions(options map[string]any) {
	a.Options = options
	a.require(agentFieldOptions)
}

// SetSteps sets the Steps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetSteps(steps *float64) {
	a.Steps = steps
	a.require(agentFieldSteps)
}

func (a *Agent) UnmarshalJSON(data []byte) error {
	type unmarshaler Agent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = Agent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *Agent) MarshalJSON() ([]byte, error) {
	type embed Agent
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *Agent) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AgentMode string

const (
	AgentModeSubagent AgentMode = "subagent"
	AgentModePrimary  AgentMode = "primary"
	AgentModeAll      AgentMode = "all"
)

func NewAgentModeFromString(s string) (AgentMode, error) {
	switch s {
	case "subagent":
		return AgentModeSubagent, nil
	case "primary":
		return AgentModePrimary, nil
	case "all":
		return AgentModeAll, nil
	}
	var t AgentMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentMode) Ptr() *AgentMode {
	return &a
}

var (
	agentModelFieldModelID    = big.NewInt(1 << 0)
	agentModelFieldProviderID = big.NewInt(1 << 1)
)

type AgentModel struct {
	ModelID    string `json:"modelID" url:"modelID"`
	ProviderID string `json:"providerID" url:"providerID"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentModel) GetModelID() string {
	if a == nil {
		return ""
	}
	return a.ModelID
}

func (a *AgentModel) GetProviderID() string {
	if a == nil {
		return ""
	}
	return a.ProviderID
}

func (a *AgentModel) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentModel) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetModelID sets the ModelID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentModel) SetModelID(modelID string) {
	a.ModelID = modelID
	a.require(agentModelFieldModelID)
}

// SetProviderID sets the ProviderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentModel) SetProviderID(providerID string) {
	a.ProviderID = providerID
	a.require(agentModelFieldProviderID)
}

func (a *AgentModel) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentModel
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentModel(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentModel) MarshalJSON() ([]byte, error) {
	type embed AgentModel
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentModel) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}
