// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersPermissionListRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &PermissionListRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &PermissionListRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPermissionListRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PermissionListRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PermissionListRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPermissionReplyRequest(t *testing.T) {
	t.Run("SetRequestID", func(t *testing.T) {
		obj := &PermissionReplyRequest{}
		var fernTestValueRequestID string
		obj.SetRequestID(fernTestValueRequestID)
		assert.Equal(t, fernTestValueRequestID, obj.RequestID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDirectory", func(t *testing.T) {
		obj := &PermissionReplyRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &PermissionReplyRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReply", func(t *testing.T) {
		obj := &PermissionReplyRequest{}
		var fernTestValueReply PermissionReplyRequestReply
		obj.SetReply(fernTestValueReply)
		assert.Equal(t, fernTestValueReply, obj.Reply)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMessage", func(t *testing.T) {
		obj := &PermissionReplyRequest{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPermissionReplyRequest(t *testing.T) {
	t.Run("SetRequestID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PermissionReplyRequest{}
		var fernTestValueRequestID string

		// Act
		obj.SetRequestID(fernTestValueRequestID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PermissionReplyRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PermissionReplyRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReply_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PermissionReplyRequest{}
		var fernTestValueReply PermissionReplyRequestReply

		// Act
		obj.SetReply(fernTestValueReply)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PermissionReplyRequest{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumPermissionReplyRequestReply(t *testing.T) {
	t.Run("NewFromString_once", func(t *testing.T) {
		t.Parallel()
		val, err := NewPermissionReplyRequestReplyFromString("once")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, PermissionReplyRequestReply("once"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_always", func(t *testing.T) {
		t.Parallel()
		val, err := NewPermissionReplyRequestReplyFromString("always")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, PermissionReplyRequestReply("always"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_reject", func(t *testing.T) {
		t.Parallel()
		val, err := NewPermissionReplyRequestReplyFromString("reject")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, PermissionReplyRequestReply("reject"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewPermissionReplyRequestReplyFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewPermissionReplyRequestReplyFromString("once")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
