// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersProjectCurrentRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectCurrentRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectCurrentRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectCurrentRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCurrentRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCurrentRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectDirectoriesRequest(t *testing.T) {
	t.Run("SetProjectID", func(t *testing.T) {
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueProjectID string
		obj.SetProjectID(fernTestValueProjectID)
		assert.Equal(t, fernTestValueProjectID, obj.ProjectID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectDirectoriesRequest(t *testing.T) {
	t.Run("SetProjectID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueProjectID string

		// Act
		obj.SetProjectID(fernTestValueProjectID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectInitGitRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectInitGitRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectInitGitRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectInitGitRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectInitGitRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectInitGitRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectListRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectListRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectListRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectListRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectListRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectListRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProject(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorktree", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueWorktree string
		obj.SetWorktree(fernTestValueWorktree)
		assert.Equal(t, fernTestValueWorktree, obj.Worktree)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVcs", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueVcs *ProjectVcs
		obj.SetVcs(fernTestValueVcs)
		assert.Equal(t, fernTestValueVcs, obj.Vcs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIcon", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueIcon *ProjectIcon
		obj.SetIcon(fernTestValueIcon)
		assert.Equal(t, fernTestValueIcon, obj.Icon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCommands", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueCommands *ProjectCommands
		obj.SetCommands(fernTestValueCommands)
		assert.Equal(t, fernTestValueCommands, obj.Commands)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTime", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueTime *ProjectTime
		obj.SetTime(fernTestValueTime)
		assert.Equal(t, fernTestValueTime, obj.Time)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSandboxes", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueSandboxes []string
		obj.SetSandboxes(fernTestValueSandboxes)
		assert.Equal(t, fernTestValueSandboxes, obj.Sandboxes)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProject(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetWorktree", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected string
		obj.Worktree = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWorktree(), "getter should return the property value")
	})

	t.Run("GetWorktree_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWorktree() // Should return zero value
	})

	t.Run("GetVcs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectVcs
		obj.Vcs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVcs(), "getter should return the property value")
	})

	t.Run("GetVcs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Vcs = nil

		// Act & Assert
		assert.Nil(t, obj.GetVcs(), "getter should return nil when property is nil")
	})

	t.Run("GetVcs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVcs() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetIcon", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectIcon
		obj.Icon = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIcon(), "getter should return the property value")
	})

	t.Run("GetIcon_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Icon = nil

		// Act & Assert
		assert.Nil(t, obj.GetIcon(), "getter should return nil when property is nil")
	})

	t.Run("GetIcon_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIcon() // Should return zero value
	})

	t.Run("GetCommands", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectCommands
		obj.Commands = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCommands(), "getter should return the property value")
	})

	t.Run("GetCommands_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Commands = nil

		// Act & Assert
		assert.Nil(t, obj.GetCommands(), "getter should return nil when property is nil")
	})

	t.Run("GetCommands_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCommands() // Should return zero value
	})

	t.Run("GetTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectTime
		obj.Time = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTime(), "getter should return the property value")
	})

	t.Run("GetTime_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Time = nil

		// Act & Assert
		assert.Nil(t, obj.GetTime(), "getter should return nil when property is nil")
	})

	t.Run("GetTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTime() // Should return zero value
	})

	t.Run("GetSandboxes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected []string
		obj.Sandboxes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSandboxes(), "getter should return the property value")
	})

	t.Run("GetSandboxes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Sandboxes = nil

		// Act & Assert
		assert.Nil(t, obj.GetSandboxes(), "getter should return nil when property is nil")
	})

	t.Run("GetSandboxes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSandboxes() // Should return zero value
	})

}

func TestSettersMarkExplicitProject(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorktree_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueWorktree string

		// Act
		obj.SetWorktree(fernTestValueWorktree)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVcs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueVcs *ProjectVcs

		// Act
		obj.SetVcs(fernTestValueVcs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIcon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueIcon *ProjectIcon

		// Act
		obj.SetIcon(fernTestValueIcon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCommands_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueCommands *ProjectCommands

		// Act
		obj.SetCommands(fernTestValueCommands)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueTime *ProjectTime

		// Act
		obj.SetTime(fernTestValueTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSandboxes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueSandboxes []string

		// Act
		obj.SetSandboxes(fernTestValueSandboxes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectCommands(t *testing.T) {
	t.Run("SetStart", func(t *testing.T) {
		obj := &ProjectCommands{}
		var fernTestValueStart *string
		obj.SetStart(fernTestValueStart)
		assert.Equal(t, fernTestValueStart, obj.Start)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProjectCommands(t *testing.T) {
	t.Run("GetStart", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCommands{}
		var expected *string
		obj.Start = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStart(), "getter should return the property value")
	})

	t.Run("GetStart_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCommands{}
		obj.Start = nil

		// Act & Assert
		assert.Nil(t, obj.GetStart(), "getter should return nil when property is nil")
	})

	t.Run("GetStart_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectCommands
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStart() // Should return zero value
	})

}

func TestSettersMarkExplicitProjectCommands(t *testing.T) {
	t.Run("SetStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCommands{}
		var fernTestValueStart *string

		// Act
		obj.SetStart(fernTestValueStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectDirectoriesItem(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectDirectoriesItem{}
		var fernTestValueDirectory string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStrategy", func(t *testing.T) {
		obj := &ProjectDirectoriesItem{}
		var fernTestValueStrategy *string
		obj.SetStrategy(fernTestValueStrategy)
		assert.Equal(t, fernTestValueStrategy, obj.Strategy)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProjectDirectoriesItem(t *testing.T) {
	t.Run("GetDirectory", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var expected string
		obj.Directory = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDirectory(), "getter should return the property value")
	})

	t.Run("GetDirectory_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDirectory() // Should return zero value
	})

	t.Run("GetStrategy", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var expected *string
		obj.Strategy = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStrategy(), "getter should return the property value")
	})

	t.Run("GetStrategy_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		obj.Strategy = nil

		// Act & Assert
		assert.Nil(t, obj.GetStrategy(), "getter should return nil when property is nil")
	})

	t.Run("GetStrategy_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStrategy() // Should return zero value
	})

}

func TestSettersMarkExplicitProjectDirectoriesItem(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var fernTestValueDirectory string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStrategy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var fernTestValueStrategy *string

		// Act
		obj.SetStrategy(fernTestValueStrategy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectIcon(t *testing.T) {
	t.Run("SetURL", func(t *testing.T) {
		obj := &ProjectIcon{}
		var fernTestValueURL *string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOverride", func(t *testing.T) {
		obj := &ProjectIcon{}
		var fernTestValueOverride *string
		obj.SetOverride(fernTestValueOverride)
		assert.Equal(t, fernTestValueOverride, obj.Override)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetColor", func(t *testing.T) {
		obj := &ProjectIcon{}
		var fernTestValueColor *string
		obj.SetColor(fernTestValueColor)
		assert.Equal(t, fernTestValueColor, obj.Color)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProjectIcon(t *testing.T) {
	t.Run("GetURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		var expected *string
		obj.URL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURL(), "getter should return the property value")
	})

	t.Run("GetURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		obj.URL = nil

		// Act & Assert
		assert.Nil(t, obj.GetURL(), "getter should return nil when property is nil")
	})

	t.Run("GetURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectIcon
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURL() // Should return zero value
	})

	t.Run("GetOverride", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		var expected *string
		obj.Override = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOverride(), "getter should return the property value")
	})

	t.Run("GetOverride_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		obj.Override = nil

		// Act & Assert
		assert.Nil(t, obj.GetOverride(), "getter should return nil when property is nil")
	})

	t.Run("GetOverride_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectIcon
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOverride() // Should return zero value
	})

	t.Run("GetColor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		var expected *string
		obj.Color = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetColor(), "getter should return the property value")
	})

	t.Run("GetColor_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		obj.Color = nil

		// Act & Assert
		assert.Nil(t, obj.GetColor(), "getter should return nil when property is nil")
	})

	t.Run("GetColor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectIcon
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetColor() // Should return zero value
	})

}

func TestSettersMarkExplicitProjectIcon(t *testing.T) {
	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		var fernTestValueURL *string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOverride_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		var fernTestValueOverride *string

		// Act
		obj.SetOverride(fernTestValueOverride)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetColor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}
		var fernTestValueColor *string

		// Act
		obj.SetColor(fernTestValueColor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectTime(t *testing.T) {
	t.Run("SetCreated", func(t *testing.T) {
		obj := &ProjectTime{}
		var fernTestValueCreated int
		obj.SetCreated(fernTestValueCreated)
		assert.Equal(t, fernTestValueCreated, obj.Created)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdated", func(t *testing.T) {
		obj := &ProjectTime{}
		var fernTestValueUpdated int
		obj.SetUpdated(fernTestValueUpdated)
		assert.Equal(t, fernTestValueUpdated, obj.Updated)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInitialized", func(t *testing.T) {
		obj := &ProjectTime{}
		var fernTestValueInitialized *int
		obj.SetInitialized(fernTestValueInitialized)
		assert.Equal(t, fernTestValueInitialized, obj.Initialized)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProjectTime(t *testing.T) {
	t.Run("GetCreated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}
		var expected int
		obj.Created = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreated(), "getter should return the property value")
	})

	t.Run("GetCreated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectTime
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreated() // Should return zero value
	})

	t.Run("GetUpdated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}
		var expected int
		obj.Updated = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdated(), "getter should return the property value")
	})

	t.Run("GetUpdated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectTime
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdated() // Should return zero value
	})

	t.Run("GetInitialized", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}
		var expected *int
		obj.Initialized = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInitialized(), "getter should return the property value")
	})

	t.Run("GetInitialized_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}
		obj.Initialized = nil

		// Act & Assert
		assert.Nil(t, obj.GetInitialized(), "getter should return nil when property is nil")
	})

	t.Run("GetInitialized_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectTime
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInitialized() // Should return zero value
	})

}

func TestSettersMarkExplicitProjectTime(t *testing.T) {
	t.Run("SetCreated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}
		var fernTestValueCreated int

		// Act
		obj.SetCreated(fernTestValueCreated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}
		var fernTestValueUpdated int

		// Act
		obj.SetUpdated(fernTestValueUpdated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInitialized_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}
		var fernTestValueInitialized *int

		// Act
		obj.SetInitialized(fernTestValueInitialized)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectUpdateRequestCommands(t *testing.T) {
	t.Run("SetStart", func(t *testing.T) {
		obj := &ProjectUpdateRequestCommands{}
		var fernTestValueStart *string
		obj.SetStart(fernTestValueStart)
		assert.Equal(t, fernTestValueStart, obj.Start)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProjectUpdateRequestCommands(t *testing.T) {
	t.Run("GetStart", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestCommands{}
		var expected *string
		obj.Start = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStart(), "getter should return the property value")
	})

	t.Run("GetStart_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestCommands{}
		obj.Start = nil

		// Act & Assert
		assert.Nil(t, obj.GetStart(), "getter should return nil when property is nil")
	})

	t.Run("GetStart_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestCommands
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStart() // Should return zero value
	})

}

func TestSettersMarkExplicitProjectUpdateRequestCommands(t *testing.T) {
	t.Run("SetStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestCommands{}
		var fernTestValueStart *string

		// Act
		obj.SetStart(fernTestValueStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectUpdateRequestIcon(t *testing.T) {
	t.Run("SetURL", func(t *testing.T) {
		obj := &ProjectUpdateRequestIcon{}
		var fernTestValueURL *string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOverride", func(t *testing.T) {
		obj := &ProjectUpdateRequestIcon{}
		var fernTestValueOverride *string
		obj.SetOverride(fernTestValueOverride)
		assert.Equal(t, fernTestValueOverride, obj.Override)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetColor", func(t *testing.T) {
		obj := &ProjectUpdateRequestIcon{}
		var fernTestValueColor *string
		obj.SetColor(fernTestValueColor)
		assert.Equal(t, fernTestValueColor, obj.Color)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProjectUpdateRequestIcon(t *testing.T) {
	t.Run("GetURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		var expected *string
		obj.URL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURL(), "getter should return the property value")
	})

	t.Run("GetURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		obj.URL = nil

		// Act & Assert
		assert.Nil(t, obj.GetURL(), "getter should return nil when property is nil")
	})

	t.Run("GetURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestIcon
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURL() // Should return zero value
	})

	t.Run("GetOverride", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		var expected *string
		obj.Override = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOverride(), "getter should return the property value")
	})

	t.Run("GetOverride_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		obj.Override = nil

		// Act & Assert
		assert.Nil(t, obj.GetOverride(), "getter should return nil when property is nil")
	})

	t.Run("GetOverride_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestIcon
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOverride() // Should return zero value
	})

	t.Run("GetColor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		var expected *string
		obj.Color = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetColor(), "getter should return the property value")
	})

	t.Run("GetColor_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		obj.Color = nil

		// Act & Assert
		assert.Nil(t, obj.GetColor(), "getter should return nil when property is nil")
	})

	t.Run("GetColor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestIcon
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetColor() // Should return zero value
	})

}

func TestSettersMarkExplicitProjectUpdateRequestIcon(t *testing.T) {
	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		var fernTestValueURL *string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOverride_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		var fernTestValueOverride *string

		// Act
		obj.SetOverride(fernTestValueOverride)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetColor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}
		var fernTestValueColor *string

		// Act
		obj.SetColor(fernTestValueColor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectUpdateRequest(t *testing.T) {
	t.Run("SetProjectID", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueProjectID string
		obj.SetProjectID(fernTestValueProjectID)
		assert.Equal(t, fernTestValueProjectID, obj.ProjectID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIcon", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueIcon *ProjectUpdateRequestIcon
		obj.SetIcon(fernTestValueIcon)
		assert.Equal(t, fernTestValueIcon, obj.Icon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCommands", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueCommands *ProjectUpdateRequestCommands
		obj.SetCommands(fernTestValueCommands)
		assert.Equal(t, fernTestValueCommands, obj.Commands)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectUpdateRequest(t *testing.T) {
	t.Run("SetProjectID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueProjectID string

		// Act
		obj.SetProjectID(fernTestValueProjectID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIcon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueIcon *ProjectUpdateRequestIcon

		// Act
		obj.SetIcon(fernTestValueIcon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCommands_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueCommands *ProjectUpdateRequestCommands

		// Act
		obj.SetCommands(fernTestValueCommands)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingProject(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Project
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Project
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Project
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProjectCommands(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCommands{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProjectCommands
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProjectCommands
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProjectCommands
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProjectDirectoriesItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProjectDirectoriesItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProjectDirectoriesItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProjectDirectoriesItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProjectIcon(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectIcon{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProjectIcon
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProjectIcon
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProjectIcon
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProjectTime(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectTime{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProjectTime
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProjectTime
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProjectTime
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProjectUpdateRequestCommands(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestCommands{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProjectUpdateRequestCommands
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProjectUpdateRequestCommands
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProjectUpdateRequestCommands
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProjectUpdateRequestIcon(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequestIcon{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProjectUpdateRequestIcon
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProjectUpdateRequestIcon
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProjectUpdateRequestIcon
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringProject(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Project{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProjectCommands(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectCommands{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectCommands
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProjectDirectoriesItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectDirectoriesItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProjectIcon(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectIcon{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectIcon
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProjectTime(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectTime{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectTime
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProjectUpdateRequestCommands(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectUpdateRequestCommands{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestCommands
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProjectUpdateRequestIcon(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectUpdateRequestIcon{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestIcon
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumProjectVcs(t *testing.T) {
	t.Run("NewFromString_git", func(t *testing.T) {
		t.Parallel()
		val, err := NewProjectVcsFromString("git")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ProjectVcs("git"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewProjectVcsFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewProjectVcsFromString("git")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesProject(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Project{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProjectCommands(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectCommands{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectCommands
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProjectDirectoriesItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectDirectoriesItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProjectIcon(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectIcon{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectIcon
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProjectTime(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectTime{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectTime
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProjectUpdateRequestCommands(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectUpdateRequestCommands{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestCommands
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProjectUpdateRequestIcon(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectUpdateRequestIcon{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectUpdateRequestIcon
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
