// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Acksell/opencode-go-sdk/sdk/internal"
	big "math/big"
)

var (
	projectCurrentRequestFieldDirectory = big.NewInt(1 << 0)
	projectCurrentRequestFieldWorkspace = big.NewInt(1 << 1)
)

type ProjectCurrentRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProjectCurrentRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectCurrentRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(projectCurrentRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectCurrentRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(projectCurrentRequestFieldWorkspace)
}

var (
	projectInitGitRequestFieldDirectory = big.NewInt(1 << 0)
	projectInitGitRequestFieldWorkspace = big.NewInt(1 << 1)
)

type ProjectInitGitRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProjectInitGitRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectInitGitRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(projectInitGitRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectInitGitRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(projectInitGitRequestFieldWorkspace)
}

var (
	projectListRequestFieldDirectory = big.NewInt(1 << 0)
	projectListRequestFieldWorkspace = big.NewInt(1 << 1)
)

type ProjectListRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProjectListRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectListRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(projectListRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectListRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(projectListRequestFieldWorkspace)
}

var (
	projectUpdateRequestCommandsFieldStart = big.NewInt(1 << 0)
)

type ProjectUpdateRequestCommands struct {
	// Startup script to run when creating a new workspace (worktree)
	Start *string `json:"start,omitempty" url:"start,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProjectUpdateRequestCommands) GetStart() *string {
	if p == nil {
		return nil
	}
	return p.Start
}

func (p *ProjectUpdateRequestCommands) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProjectUpdateRequestCommands) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequestCommands) SetStart(start *string) {
	p.Start = start
	p.require(projectUpdateRequestCommandsFieldStart)
}

func (p *ProjectUpdateRequestCommands) UnmarshalJSON(data []byte) error {
	type unmarshaler ProjectUpdateRequestCommands
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProjectUpdateRequestCommands(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProjectUpdateRequestCommands) MarshalJSON() ([]byte, error) {
	type embed ProjectUpdateRequestCommands
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProjectUpdateRequestCommands) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	projectUpdateRequestIconFieldURL      = big.NewInt(1 << 0)
	projectUpdateRequestIconFieldOverride = big.NewInt(1 << 1)
	projectUpdateRequestIconFieldColor    = big.NewInt(1 << 2)
)

type ProjectUpdateRequestIcon struct {
	URL      *string `json:"url,omitempty" url:"url,omitempty"`
	Override *string `json:"override,omitempty" url:"override,omitempty"`
	Color    *string `json:"color,omitempty" url:"color,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProjectUpdateRequestIcon) GetURL() *string {
	if p == nil {
		return nil
	}
	return p.URL
}

func (p *ProjectUpdateRequestIcon) GetOverride() *string {
	if p == nil {
		return nil
	}
	return p.Override
}

func (p *ProjectUpdateRequestIcon) GetColor() *string {
	if p == nil {
		return nil
	}
	return p.Color
}

func (p *ProjectUpdateRequestIcon) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProjectUpdateRequestIcon) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequestIcon) SetURL(url *string) {
	p.URL = url
	p.require(projectUpdateRequestIconFieldURL)
}

// SetOverride sets the Override field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequestIcon) SetOverride(override *string) {
	p.Override = override
	p.require(projectUpdateRequestIconFieldOverride)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequestIcon) SetColor(color *string) {
	p.Color = color
	p.require(projectUpdateRequestIconFieldColor)
}

func (p *ProjectUpdateRequestIcon) UnmarshalJSON(data []byte) error {
	type unmarshaler ProjectUpdateRequestIcon
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProjectUpdateRequestIcon(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProjectUpdateRequestIcon) MarshalJSON() ([]byte, error) {
	type embed ProjectUpdateRequestIcon
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProjectUpdateRequestIcon) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	projectUpdateRequestFieldProjectID = big.NewInt(1 << 0)
	projectUpdateRequestFieldDirectory = big.NewInt(1 << 1)
	projectUpdateRequestFieldWorkspace = big.NewInt(1 << 2)
	projectUpdateRequestFieldName      = big.NewInt(1 << 3)
	projectUpdateRequestFieldIcon      = big.NewInt(1 << 4)
	projectUpdateRequestFieldCommands  = big.NewInt(1 << 5)
)

type ProjectUpdateRequest struct {
	ProjectID string                        `json:"-" url:"-"`
	Directory *string                       `json:"-" url:"directory,omitempty"`
	Workspace *string                       `json:"-" url:"workspace,omitempty"`
	Name      *string                       `json:"name,omitempty" url:"-"`
	Icon      *ProjectUpdateRequestIcon     `json:"icon,omitempty" url:"-"`
	Commands  *ProjectUpdateRequestCommands `json:"commands,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProjectUpdateRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequest) SetProjectID(projectID string) {
	p.ProjectID = projectID
	p.require(projectUpdateRequestFieldProjectID)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(projectUpdateRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(projectUpdateRequestFieldWorkspace)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequest) SetName(name *string) {
	p.Name = name
	p.require(projectUpdateRequestFieldName)
}

// SetIcon sets the Icon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequest) SetIcon(icon *ProjectUpdateRequestIcon) {
	p.Icon = icon
	p.require(projectUpdateRequestFieldIcon)
}

// SetCommands sets the Commands field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProjectUpdateRequest) SetCommands(commands *ProjectUpdateRequestCommands) {
	p.Commands = commands
	p.require(projectUpdateRequestFieldCommands)
}

func (p *ProjectUpdateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ProjectUpdateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = ProjectUpdateRequest(body)
	return nil
}

func (p *ProjectUpdateRequest) MarshalJSON() ([]byte, error) {
	type embed ProjectUpdateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}
