// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersProjectCurrentRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectCurrentRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectCurrentRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectCurrentRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCurrentRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectCurrentRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectDirectoriesRequest(t *testing.T) {
	t.Run("SetProjectID", func(t *testing.T) {
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueProjectID string
		obj.SetProjectID(fernTestValueProjectID)
		assert.Equal(t, fernTestValueProjectID, obj.ProjectID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectDirectoriesRequest(t *testing.T) {
	t.Run("SetProjectID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueProjectID string

		// Act
		obj.SetProjectID(fernTestValueProjectID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectInitGitRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectInitGitRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectInitGitRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectInitGitRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectInitGitRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectInitGitRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectListRequest(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectListRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectListRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectListRequest(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectListRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectListRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProject(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorktree", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueWorktree string
		obj.SetWorktree(fernTestValueWorktree)
		assert.Equal(t, fernTestValueWorktree, obj.Worktree)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVcs", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueVcs *ProjectVcs
		obj.SetVcs(fernTestValueVcs)
		assert.Equal(t, fernTestValueVcs, obj.Vcs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIcon", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueIcon *ProjectIcon
		obj.SetIcon(fernTestValueIcon)
		assert.Equal(t, fernTestValueIcon, obj.Icon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCommands", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueCommands *ProjectCommands
		obj.SetCommands(fernTestValueCommands)
		assert.Equal(t, fernTestValueCommands, obj.Commands)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTime", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueTime *ProjectTime
		obj.SetTime(fernTestValueTime)
		assert.Equal(t, fernTestValueTime, obj.Time)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSandboxes", func(t *testing.T) {
		obj := &Project{}
		var fernTestValueSandboxes []string
		obj.SetSandboxes(fernTestValueSandboxes)
		assert.Equal(t, fernTestValueSandboxes, obj.Sandboxes)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProject(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetWorktree", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected string
		obj.Worktree = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWorktree(), "getter should return the property value")
	})

	t.Run("GetWorktree_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWorktree() // Should return zero value
	})

	t.Run("GetVcs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectVcs
		obj.Vcs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVcs(), "getter should return the property value")
	})

	t.Run("GetVcs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Vcs = nil

		// Act & Assert
		assert.Nil(t, obj.GetVcs(), "getter should return nil when property is nil")
	})

	t.Run("GetVcs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVcs() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetIcon", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectIcon
		obj.Icon = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIcon(), "getter should return the property value")
	})

	t.Run("GetIcon_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Icon = nil

		// Act & Assert
		assert.Nil(t, obj.GetIcon(), "getter should return nil when property is nil")
	})

	t.Run("GetIcon_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIcon() // Should return zero value
	})

	t.Run("GetCommands", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectCommands
		obj.Commands = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCommands(), "getter should return the property value")
	})

	t.Run("GetCommands_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Commands = nil

		// Act & Assert
		assert.Nil(t, obj.GetCommands(), "getter should return nil when property is nil")
	})

	t.Run("GetCommands_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCommands() // Should return zero value
	})

	t.Run("GetTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected *ProjectTime
		obj.Time = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTime(), "getter should return the property value")
	})

	t.Run("GetTime_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Time = nil

		// Act & Assert
		assert.Nil(t, obj.GetTime(), "getter should return nil when property is nil")
	})

	t.Run("GetTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTime() // Should return zero value
	})

	t.Run("GetSandboxes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var expected []string
		obj.Sandboxes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSandboxes(), "getter should return the property value")
	})

	t.Run("GetSandboxes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		obj.Sandboxes = nil

		// Act & Assert
		assert.Nil(t, obj.GetSandboxes(), "getter should return nil when property is nil")
	})

	t.Run("GetSandboxes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSandboxes() // Should return zero value
	})

}

func TestSettersMarkExplicitProject(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorktree_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueWorktree string

		// Act
		obj.SetWorktree(fernTestValueWorktree)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVcs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueVcs *ProjectVcs

		// Act
		obj.SetVcs(fernTestValueVcs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIcon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueIcon *ProjectIcon

		// Act
		obj.SetIcon(fernTestValueIcon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCommands_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueCommands *ProjectCommands

		// Act
		obj.SetCommands(fernTestValueCommands)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueTime *ProjectTime

		// Act
		obj.SetTime(fernTestValueTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSandboxes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}
		var fernTestValueSandboxes []string

		// Act
		obj.SetSandboxes(fernTestValueSandboxes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectDirectoriesItem(t *testing.T) {
	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectDirectoriesItem{}
		var fernTestValueDirectory string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStrategy", func(t *testing.T) {
		obj := &ProjectDirectoriesItem{}
		var fernTestValueStrategy *string
		obj.SetStrategy(fernTestValueStrategy)
		assert.Equal(t, fernTestValueStrategy, obj.Strategy)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersProjectDirectoriesItem(t *testing.T) {
	t.Run("GetDirectory", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var expected string
		obj.Directory = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDirectory(), "getter should return the property value")
	})

	t.Run("GetDirectory_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDirectory() // Should return zero value
	})

	t.Run("GetStrategy", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var expected *string
		obj.Strategy = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStrategy(), "getter should return the property value")
	})

	t.Run("GetStrategy_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		obj.Strategy = nil

		// Act & Assert
		assert.Nil(t, obj.GetStrategy(), "getter should return nil when property is nil")
	})

	t.Run("GetStrategy_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStrategy() // Should return zero value
	})

}

func TestSettersMarkExplicitProjectDirectoriesItem(t *testing.T) {
	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var fernTestValueDirectory string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStrategy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}
		var fernTestValueStrategy *string

		// Act
		obj.SetStrategy(fernTestValueStrategy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProjectUpdateRequest(t *testing.T) {
	t.Run("SetProjectID", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueProjectID string
		obj.SetProjectID(fernTestValueProjectID)
		assert.Equal(t, fernTestValueProjectID, obj.ProjectID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDirectory", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueDirectory *string
		obj.SetDirectory(fernTestValueDirectory)
		assert.Equal(t, fernTestValueDirectory, obj.Directory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWorkspace", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueWorkspace *string
		obj.SetWorkspace(fernTestValueWorkspace)
		assert.Equal(t, fernTestValueWorkspace, obj.Workspace)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIcon", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueIcon *ProjectIcon
		obj.SetIcon(fernTestValueIcon)
		assert.Equal(t, fernTestValueIcon, obj.Icon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCommands", func(t *testing.T) {
		obj := &ProjectUpdateRequest{}
		var fernTestValueCommands *ProjectCommands
		obj.SetCommands(fernTestValueCommands)
		assert.Equal(t, fernTestValueCommands, obj.Commands)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProjectUpdateRequest(t *testing.T) {
	t.Run("SetProjectID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueProjectID string

		// Act
		obj.SetProjectID(fernTestValueProjectID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDirectory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueDirectory *string

		// Act
		obj.SetDirectory(fernTestValueDirectory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWorkspace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueWorkspace *string

		// Act
		obj.SetWorkspace(fernTestValueWorkspace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIcon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueIcon *ProjectIcon

		// Act
		obj.SetIcon(fernTestValueIcon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCommands_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectUpdateRequest{}
		var fernTestValueCommands *ProjectCommands

		// Act
		obj.SetCommands(fernTestValueCommands)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingProject(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Project{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Project
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Project
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Project
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingProjectDirectoriesItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProjectDirectoriesItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ProjectDirectoriesItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ProjectDirectoriesItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ProjectDirectoriesItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringProject(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Project{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringProjectDirectoriesItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectDirectoriesItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesProject(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Project{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Project
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesProjectDirectoriesItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ProjectDirectoriesItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ProjectDirectoriesItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
