// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Acksell/opencode-go-sdk/sdk/internal"
	big "math/big"
)

var (
	providerAuthRequestFieldDirectory = big.NewInt(1 << 0)
	providerAuthRequestFieldWorkspace = big.NewInt(1 << 1)
)

type ProviderAuthRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderAuthRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(providerAuthRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(providerAuthRequestFieldWorkspace)
}

var (
	providerListRequestFieldDirectory = big.NewInt(1 << 0)
	providerListRequestFieldWorkspace = big.NewInt(1 << 1)
)

type ProviderListRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderListRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderListRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(providerListRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderListRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(providerListRequestFieldWorkspace)
}

var (
	providerOauthAuthorizeRequestFieldProviderID = big.NewInt(1 << 0)
	providerOauthAuthorizeRequestFieldDirectory  = big.NewInt(1 << 1)
	providerOauthAuthorizeRequestFieldWorkspace  = big.NewInt(1 << 2)
	providerOauthAuthorizeRequestFieldMethod     = big.NewInt(1 << 3)
	providerOauthAuthorizeRequestFieldInputs     = big.NewInt(1 << 4)
)

type ProviderOauthAuthorizeRequest struct {
	ProviderID string  `json:"-" url:"-"`
	Directory  *string `json:"-" url:"directory,omitempty"`
	Workspace  *string `json:"-" url:"workspace,omitempty"`
	// Auth method index
	Method float64           `json:"method" url:"-"`
	Inputs map[string]string `json:"inputs,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderOauthAuthorizeRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProviderID sets the ProviderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthAuthorizeRequest) SetProviderID(providerID string) {
	p.ProviderID = providerID
	p.require(providerOauthAuthorizeRequestFieldProviderID)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthAuthorizeRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(providerOauthAuthorizeRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthAuthorizeRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(providerOauthAuthorizeRequestFieldWorkspace)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthAuthorizeRequest) SetMethod(method float64) {
	p.Method = method
	p.require(providerOauthAuthorizeRequestFieldMethod)
}

// SetInputs sets the Inputs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthAuthorizeRequest) SetInputs(inputs map[string]string) {
	p.Inputs = inputs
	p.require(providerOauthAuthorizeRequestFieldInputs)
}

func (p *ProviderOauthAuthorizeRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderOauthAuthorizeRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = ProviderOauthAuthorizeRequest(body)
	return nil
}

func (p *ProviderOauthAuthorizeRequest) MarshalJSON() ([]byte, error) {
	type embed ProviderOauthAuthorizeRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	providerOauthCallbackRequestFieldProviderID = big.NewInt(1 << 0)
	providerOauthCallbackRequestFieldDirectory  = big.NewInt(1 << 1)
	providerOauthCallbackRequestFieldWorkspace  = big.NewInt(1 << 2)
	providerOauthCallbackRequestFieldMethod     = big.NewInt(1 << 3)
	providerOauthCallbackRequestFieldCode       = big.NewInt(1 << 4)
)

type ProviderOauthCallbackRequest struct {
	ProviderID string  `json:"-" url:"-"`
	Directory  *string `json:"-" url:"directory,omitempty"`
	Workspace  *string `json:"-" url:"workspace,omitempty"`
	// Auth method index
	Method float64 `json:"method" url:"-"`
	Code   *string `json:"code,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProviderOauthCallbackRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetProviderID sets the ProviderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthCallbackRequest) SetProviderID(providerID string) {
	p.ProviderID = providerID
	p.require(providerOauthCallbackRequestFieldProviderID)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthCallbackRequest) SetDirectory(directory *string) {
	p.Directory = directory
	p.require(providerOauthCallbackRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthCallbackRequest) SetWorkspace(workspace *string) {
	p.Workspace = workspace
	p.require(providerOauthCallbackRequestFieldWorkspace)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthCallbackRequest) SetMethod(method float64) {
	p.Method = method
	p.require(providerOauthCallbackRequestFieldMethod)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderOauthCallbackRequest) SetCode(code *string) {
	p.Code = code
	p.require(providerOauthCallbackRequestFieldCode)
}

func (p *ProviderOauthCallbackRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderOauthCallbackRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = ProviderOauthCallbackRequest(body)
	return nil
}

func (p *ProviderOauthCallbackRequest) MarshalJSON() ([]byte, error) {
	type embed ProviderOauthCallbackRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	providerAuthAuthorizationFieldURL          = big.NewInt(1 << 0)
	providerAuthAuthorizationFieldMethod       = big.NewInt(1 << 1)
	providerAuthAuthorizationFieldInstructions = big.NewInt(1 << 2)
)

type ProviderAuthAuthorization struct {
	URL          string                          `json:"url" url:"url"`
	Method       ProviderAuthAuthorizationMethod `json:"method" url:"method"`
	Instructions string                          `json:"instructions" url:"instructions"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderAuthAuthorization) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

func (p *ProviderAuthAuthorization) GetMethod() ProviderAuthAuthorizationMethod {
	if p == nil {
		return ""
	}
	return p.Method
}

func (p *ProviderAuthAuthorization) GetInstructions() string {
	if p == nil {
		return ""
	}
	return p.Instructions
}

func (p *ProviderAuthAuthorization) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderAuthAuthorization) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthAuthorization) SetURL(url string) {
	p.URL = url
	p.require(providerAuthAuthorizationFieldURL)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthAuthorization) SetMethod(method ProviderAuthAuthorizationMethod) {
	p.Method = method
	p.require(providerAuthAuthorizationFieldMethod)
}

// SetInstructions sets the Instructions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthAuthorization) SetInstructions(instructions string) {
	p.Instructions = instructions
	p.require(providerAuthAuthorizationFieldInstructions)
}

func (p *ProviderAuthAuthorization) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderAuthAuthorization
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderAuthAuthorization(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderAuthAuthorization) MarshalJSON() ([]byte, error) {
	type embed ProviderAuthAuthorization
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderAuthAuthorization) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type ProviderAuthAuthorizationMethod string

const (
	ProviderAuthAuthorizationMethodAuto ProviderAuthAuthorizationMethod = "auto"
	ProviderAuthAuthorizationMethodCode ProviderAuthAuthorizationMethod = "code"
)

func NewProviderAuthAuthorizationMethodFromString(s string) (ProviderAuthAuthorizationMethod, error) {
	switch s {
	case "auto":
		return ProviderAuthAuthorizationMethodAuto, nil
	case "code":
		return ProviderAuthAuthorizationMethodCode, nil
	}
	var t ProviderAuthAuthorizationMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderAuthAuthorizationMethod) Ptr() *ProviderAuthAuthorizationMethod {
	return &p
}

var (
	providerAuthMethodFieldType    = big.NewInt(1 << 0)
	providerAuthMethodFieldLabel   = big.NewInt(1 << 1)
	providerAuthMethodFieldPrompts = big.NewInt(1 << 2)
)

type ProviderAuthMethod struct {
	Type    ProviderAuthMethodType           `json:"type" url:"type"`
	Label   string                           `json:"label" url:"label"`
	Prompts []*ProviderAuthMethodPromptsItem `json:"prompts,omitempty" url:"prompts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderAuthMethod) GetType() ProviderAuthMethodType {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *ProviderAuthMethod) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *ProviderAuthMethod) GetPrompts() []*ProviderAuthMethodPromptsItem {
	if p == nil {
		return nil
	}
	return p.Prompts
}

func (p *ProviderAuthMethod) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderAuthMethod) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethod) SetType(type_ ProviderAuthMethodType) {
	p.Type = type_
	p.require(providerAuthMethodFieldType)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethod) SetLabel(label string) {
	p.Label = label
	p.require(providerAuthMethodFieldLabel)
}

// SetPrompts sets the Prompts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethod) SetPrompts(prompts []*ProviderAuthMethodPromptsItem) {
	p.Prompts = prompts
	p.require(providerAuthMethodFieldPrompts)
}

func (p *ProviderAuthMethod) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderAuthMethod
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderAuthMethod(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderAuthMethod) MarshalJSON() ([]byte, error) {
	type embed ProviderAuthMethod
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderAuthMethod) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type ProviderAuthMethodPromptsItem struct {
	Type   string
	Text   *ProviderAuthMethodPromptsItemText
	Select *ProviderAuthMethodPromptsItemSelect
}

func (p *ProviderAuthMethodPromptsItem) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *ProviderAuthMethodPromptsItem) GetText() *ProviderAuthMethodPromptsItemText {
	if p == nil {
		return nil
	}
	return p.Text
}

func (p *ProviderAuthMethodPromptsItem) GetSelect() *ProviderAuthMethodPromptsItemSelect {
	if p == nil {
		return nil
	}
	return p.Select
}

func (p *ProviderAuthMethodPromptsItem) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	p.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", p)
	}
	switch unmarshaler.Type {
	case "text":
		value := new(ProviderAuthMethodPromptsItemText)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Text = value
	case "select":
		value := new(ProviderAuthMethodPromptsItemSelect)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Select = value
	}
	return nil
}

func (p ProviderAuthMethodPromptsItem) MarshalJSON() ([]byte, error) {
	if err := p.validate(); err != nil {
		return nil, err
	}
	if p.Text != nil {
		return internal.MarshalJSONWithExtraProperty(p.Text, "type", "text")
	}
	if p.Select != nil {
		return internal.MarshalJSONWithExtraProperty(p.Select, "type", "select")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", p)
}

type ProviderAuthMethodPromptsItemVisitor interface {
	VisitText(*ProviderAuthMethodPromptsItemText) error
	VisitSelect(*ProviderAuthMethodPromptsItemSelect) error
}

func (p *ProviderAuthMethodPromptsItem) Accept(visitor ProviderAuthMethodPromptsItemVisitor) error {
	if p.Text != nil {
		return visitor.VisitText(p.Text)
	}
	if p.Select != nil {
		return visitor.VisitSelect(p.Select)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", p)
}

func (p *ProviderAuthMethodPromptsItem) validate() error {
	if p == nil {
		return fmt.Errorf("type %T is nil", p)
	}
	var fields []string
	if p.Text != nil {
		fields = append(fields, "text")
	}
	if p.Select != nil {
		fields = append(fields, "select")
	}
	if len(fields) == 0 {
		if p.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", p, p.Type)
		}
		return fmt.Errorf("type %T is empty", p)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", p, fields)
	}
	if p.Type != "" {
		field := fields[0]
		if p.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				p,
				p.Type,
				p,
			)
		}
	}
	return nil
}

var (
	providerAuthMethodPromptsItemSelectFieldKey     = big.NewInt(1 << 0)
	providerAuthMethodPromptsItemSelectFieldMessage = big.NewInt(1 << 1)
	providerAuthMethodPromptsItemSelectFieldOptions = big.NewInt(1 << 2)
	providerAuthMethodPromptsItemSelectFieldWhen    = big.NewInt(1 << 3)
)

type ProviderAuthMethodPromptsItemSelect struct {
	Key     string                                            `json:"key" url:"key"`
	Message string                                            `json:"message" url:"message"`
	Options []*ProviderAuthMethodPromptsItemSelectOptionsItem `json:"options" url:"options"`
	When    *ProviderAuthMethodPromptsItemSelectWhen          `json:"when,omitempty" url:"when,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderAuthMethodPromptsItemSelect) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *ProviderAuthMethodPromptsItemSelect) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *ProviderAuthMethodPromptsItemSelect) GetOptions() []*ProviderAuthMethodPromptsItemSelectOptionsItem {
	if p == nil {
		return nil
	}
	return p.Options
}

func (p *ProviderAuthMethodPromptsItemSelect) GetWhen() *ProviderAuthMethodPromptsItemSelectWhen {
	if p == nil {
		return nil
	}
	return p.When
}

func (p *ProviderAuthMethodPromptsItemSelect) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderAuthMethodPromptsItemSelect) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelect) SetKey(key string) {
	p.Key = key
	p.require(providerAuthMethodPromptsItemSelectFieldKey)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelect) SetMessage(message string) {
	p.Message = message
	p.require(providerAuthMethodPromptsItemSelectFieldMessage)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelect) SetOptions(options []*ProviderAuthMethodPromptsItemSelectOptionsItem) {
	p.Options = options
	p.require(providerAuthMethodPromptsItemSelectFieldOptions)
}

// SetWhen sets the When field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelect) SetWhen(when *ProviderAuthMethodPromptsItemSelectWhen) {
	p.When = when
	p.require(providerAuthMethodPromptsItemSelectFieldWhen)
}

func (p *ProviderAuthMethodPromptsItemSelect) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderAuthMethodPromptsItemSelect
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderAuthMethodPromptsItemSelect(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderAuthMethodPromptsItemSelect) MarshalJSON() ([]byte, error) {
	type embed ProviderAuthMethodPromptsItemSelect
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderAuthMethodPromptsItemSelect) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	providerAuthMethodPromptsItemSelectOptionsItemFieldLabel = big.NewInt(1 << 0)
	providerAuthMethodPromptsItemSelectOptionsItemFieldValue = big.NewInt(1 << 1)
	providerAuthMethodPromptsItemSelectOptionsItemFieldHint  = big.NewInt(1 << 2)
)

type ProviderAuthMethodPromptsItemSelectOptionsItem struct {
	Label string  `json:"label" url:"label"`
	Value string  `json:"value" url:"value"`
	Hint  *string `json:"hint,omitempty" url:"hint,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) GetValue() string {
	if p == nil {
		return ""
	}
	return p.Value
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) GetHint() *string {
	if p == nil {
		return nil
	}
	return p.Hint
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) SetLabel(label string) {
	p.Label = label
	p.require(providerAuthMethodPromptsItemSelectOptionsItemFieldLabel)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) SetValue(value string) {
	p.Value = value
	p.require(providerAuthMethodPromptsItemSelectOptionsItemFieldValue)
}

// SetHint sets the Hint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) SetHint(hint *string) {
	p.Hint = hint
	p.require(providerAuthMethodPromptsItemSelectOptionsItemFieldHint)
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderAuthMethodPromptsItemSelectOptionsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderAuthMethodPromptsItemSelectOptionsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) MarshalJSON() ([]byte, error) {
	type embed ProviderAuthMethodPromptsItemSelectOptionsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderAuthMethodPromptsItemSelectOptionsItem) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	providerAuthMethodPromptsItemSelectWhenFieldKey   = big.NewInt(1 << 0)
	providerAuthMethodPromptsItemSelectWhenFieldOp    = big.NewInt(1 << 1)
	providerAuthMethodPromptsItemSelectWhenFieldValue = big.NewInt(1 << 2)
)

type ProviderAuthMethodPromptsItemSelectWhen struct {
	Key   string                                    `json:"key" url:"key"`
	Op    ProviderAuthMethodPromptsItemSelectWhenOp `json:"op" url:"op"`
	Value string                                    `json:"value" url:"value"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) GetOp() ProviderAuthMethodPromptsItemSelectWhenOp {
	if p == nil {
		return ""
	}
	return p.Op
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) GetValue() string {
	if p == nil {
		return ""
	}
	return p.Value
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelectWhen) SetKey(key string) {
	p.Key = key
	p.require(providerAuthMethodPromptsItemSelectWhenFieldKey)
}

// SetOp sets the Op field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelectWhen) SetOp(op ProviderAuthMethodPromptsItemSelectWhenOp) {
	p.Op = op
	p.require(providerAuthMethodPromptsItemSelectWhenFieldOp)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemSelectWhen) SetValue(value string) {
	p.Value = value
	p.require(providerAuthMethodPromptsItemSelectWhenFieldValue)
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderAuthMethodPromptsItemSelectWhen
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderAuthMethodPromptsItemSelectWhen(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) MarshalJSON() ([]byte, error) {
	type embed ProviderAuthMethodPromptsItemSelectWhen
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderAuthMethodPromptsItemSelectWhen) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type ProviderAuthMethodPromptsItemSelectWhenOp string

const (
	ProviderAuthMethodPromptsItemSelectWhenOpEq  ProviderAuthMethodPromptsItemSelectWhenOp = "eq"
	ProviderAuthMethodPromptsItemSelectWhenOpNeq ProviderAuthMethodPromptsItemSelectWhenOp = "neq"
)

func NewProviderAuthMethodPromptsItemSelectWhenOpFromString(s string) (ProviderAuthMethodPromptsItemSelectWhenOp, error) {
	switch s {
	case "eq":
		return ProviderAuthMethodPromptsItemSelectWhenOpEq, nil
	case "neq":
		return ProviderAuthMethodPromptsItemSelectWhenOpNeq, nil
	}
	var t ProviderAuthMethodPromptsItemSelectWhenOp
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderAuthMethodPromptsItemSelectWhenOp) Ptr() *ProviderAuthMethodPromptsItemSelectWhenOp {
	return &p
}

var (
	providerAuthMethodPromptsItemTextFieldKey         = big.NewInt(1 << 0)
	providerAuthMethodPromptsItemTextFieldMessage     = big.NewInt(1 << 1)
	providerAuthMethodPromptsItemTextFieldPlaceholder = big.NewInt(1 << 2)
	providerAuthMethodPromptsItemTextFieldWhen        = big.NewInt(1 << 3)
)

type ProviderAuthMethodPromptsItemText struct {
	Key         string                                 `json:"key" url:"key"`
	Message     string                                 `json:"message" url:"message"`
	Placeholder *string                                `json:"placeholder,omitempty" url:"placeholder,omitempty"`
	When        *ProviderAuthMethodPromptsItemTextWhen `json:"when,omitempty" url:"when,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderAuthMethodPromptsItemText) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *ProviderAuthMethodPromptsItemText) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *ProviderAuthMethodPromptsItemText) GetPlaceholder() *string {
	if p == nil {
		return nil
	}
	return p.Placeholder
}

func (p *ProviderAuthMethodPromptsItemText) GetWhen() *ProviderAuthMethodPromptsItemTextWhen {
	if p == nil {
		return nil
	}
	return p.When
}

func (p *ProviderAuthMethodPromptsItemText) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderAuthMethodPromptsItemText) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemText) SetKey(key string) {
	p.Key = key
	p.require(providerAuthMethodPromptsItemTextFieldKey)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemText) SetMessage(message string) {
	p.Message = message
	p.require(providerAuthMethodPromptsItemTextFieldMessage)
}

// SetPlaceholder sets the Placeholder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemText) SetPlaceholder(placeholder *string) {
	p.Placeholder = placeholder
	p.require(providerAuthMethodPromptsItemTextFieldPlaceholder)
}

// SetWhen sets the When field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemText) SetWhen(when *ProviderAuthMethodPromptsItemTextWhen) {
	p.When = when
	p.require(providerAuthMethodPromptsItemTextFieldWhen)
}

func (p *ProviderAuthMethodPromptsItemText) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderAuthMethodPromptsItemText
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderAuthMethodPromptsItemText(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderAuthMethodPromptsItemText) MarshalJSON() ([]byte, error) {
	type embed ProviderAuthMethodPromptsItemText
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderAuthMethodPromptsItemText) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	providerAuthMethodPromptsItemTextWhenFieldKey   = big.NewInt(1 << 0)
	providerAuthMethodPromptsItemTextWhenFieldOp    = big.NewInt(1 << 1)
	providerAuthMethodPromptsItemTextWhenFieldValue = big.NewInt(1 << 2)
)

type ProviderAuthMethodPromptsItemTextWhen struct {
	Key   string                                  `json:"key" url:"key"`
	Op    ProviderAuthMethodPromptsItemTextWhenOp `json:"op" url:"op"`
	Value string                                  `json:"value" url:"value"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderAuthMethodPromptsItemTextWhen) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *ProviderAuthMethodPromptsItemTextWhen) GetOp() ProviderAuthMethodPromptsItemTextWhenOp {
	if p == nil {
		return ""
	}
	return p.Op
}

func (p *ProviderAuthMethodPromptsItemTextWhen) GetValue() string {
	if p == nil {
		return ""
	}
	return p.Value
}

func (p *ProviderAuthMethodPromptsItemTextWhen) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderAuthMethodPromptsItemTextWhen) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemTextWhen) SetKey(key string) {
	p.Key = key
	p.require(providerAuthMethodPromptsItemTextWhenFieldKey)
}

// SetOp sets the Op field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemTextWhen) SetOp(op ProviderAuthMethodPromptsItemTextWhenOp) {
	p.Op = op
	p.require(providerAuthMethodPromptsItemTextWhenFieldOp)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderAuthMethodPromptsItemTextWhen) SetValue(value string) {
	p.Value = value
	p.require(providerAuthMethodPromptsItemTextWhenFieldValue)
}

func (p *ProviderAuthMethodPromptsItemTextWhen) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderAuthMethodPromptsItemTextWhen
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderAuthMethodPromptsItemTextWhen(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderAuthMethodPromptsItemTextWhen) MarshalJSON() ([]byte, error) {
	type embed ProviderAuthMethodPromptsItemTextWhen
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderAuthMethodPromptsItemTextWhen) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type ProviderAuthMethodPromptsItemTextWhenOp string

const (
	ProviderAuthMethodPromptsItemTextWhenOpEq  ProviderAuthMethodPromptsItemTextWhenOp = "eq"
	ProviderAuthMethodPromptsItemTextWhenOpNeq ProviderAuthMethodPromptsItemTextWhenOp = "neq"
)

func NewProviderAuthMethodPromptsItemTextWhenOpFromString(s string) (ProviderAuthMethodPromptsItemTextWhenOp, error) {
	switch s {
	case "eq":
		return ProviderAuthMethodPromptsItemTextWhenOpEq, nil
	case "neq":
		return ProviderAuthMethodPromptsItemTextWhenOpNeq, nil
	}
	var t ProviderAuthMethodPromptsItemTextWhenOp
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderAuthMethodPromptsItemTextWhenOp) Ptr() *ProviderAuthMethodPromptsItemTextWhenOp {
	return &p
}

type ProviderAuthMethodType string

const (
	ProviderAuthMethodTypeOauth ProviderAuthMethodType = "oauth"
	ProviderAuthMethodTypeAPI   ProviderAuthMethodType = "api"
)

func NewProviderAuthMethodTypeFromString(s string) (ProviderAuthMethodType, error) {
	switch s {
	case "oauth":
		return ProviderAuthMethodTypeOauth, nil
	case "api":
		return ProviderAuthMethodTypeAPI, nil
	}
	var t ProviderAuthMethodType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProviderAuthMethodType) Ptr() *ProviderAuthMethodType {
	return &p
}

// List of providers
var (
	providerListResponseFieldAll       = big.NewInt(1 << 0)
	providerListResponseFieldDefault   = big.NewInt(1 << 1)
	providerListResponseFieldConnected = big.NewInt(1 << 2)
)

type ProviderListResponse struct {
	All       []*Provider       `json:"all" url:"all"`
	Default   map[string]string `json:"default" url:"default"`
	Connected []string          `json:"connected" url:"connected"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderListResponse) GetAll() []*Provider {
	if p == nil {
		return nil
	}
	return p.All
}

func (p *ProviderListResponse) GetDefault() map[string]string {
	if p == nil {
		return nil
	}
	return p.Default
}

func (p *ProviderListResponse) GetConnected() []string {
	if p == nil {
		return nil
	}
	return p.Connected
}

func (p *ProviderListResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProviderListResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAll sets the All field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderListResponse) SetAll(all []*Provider) {
	p.All = all
	p.require(providerListResponseFieldAll)
}

// SetDefault sets the Default field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderListResponse) SetDefault(default_ map[string]string) {
	p.Default = default_
	p.require(providerListResponseFieldDefault)
}

// SetConnected sets the Connected field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProviderListResponse) SetConnected(connected []string) {
	p.Connected = connected
	p.require(providerListResponseFieldConnected)
}

func (p *ProviderListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderListResponse) MarshalJSON() ([]byte, error) {
	type embed ProviderListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProviderListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
