// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	internal "github.com/Acksell/opencode-go-sdk/sdk/internal"
	big "math/big"
)

var (
	questionListRequestFieldDirectory = big.NewInt(1 << 0)
	questionListRequestFieldWorkspace = big.NewInt(1 << 1)
)

type QuestionListRequest struct {
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QuestionListRequest) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionListRequest) SetDirectory(directory *string) {
	q.Directory = directory
	q.require(questionListRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionListRequest) SetWorkspace(workspace *string) {
	q.Workspace = workspace
	q.require(questionListRequestFieldWorkspace)
}

var (
	questionRejectRequestFieldRequestID = big.NewInt(1 << 0)
	questionRejectRequestFieldDirectory = big.NewInt(1 << 1)
	questionRejectRequestFieldWorkspace = big.NewInt(1 << 2)
)

type QuestionRejectRequest struct {
	RequestID string  `json:"-" url:"-"`
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QuestionRejectRequest) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionRejectRequest) SetRequestID(requestID string) {
	q.RequestID = requestID
	q.require(questionRejectRequestFieldRequestID)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionRejectRequest) SetDirectory(directory *string) {
	q.Directory = directory
	q.require(questionRejectRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionRejectRequest) SetWorkspace(workspace *string) {
	q.Workspace = workspace
	q.require(questionRejectRequestFieldWorkspace)
}

var (
	questionReplyRequestFieldRequestID = big.NewInt(1 << 0)
	questionReplyRequestFieldDirectory = big.NewInt(1 << 1)
	questionReplyRequestFieldWorkspace = big.NewInt(1 << 2)
	questionReplyRequestFieldAnswers   = big.NewInt(1 << 3)
)

type QuestionReplyRequest struct {
	RequestID string  `json:"-" url:"-"`
	Directory *string `json:"-" url:"directory,omitempty"`
	Workspace *string `json:"-" url:"workspace,omitempty"`
	// User answers in order of questions (each answer is an array of selected labels)
	Answers []QuestionAnswer `json:"answers" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QuestionReplyRequest) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionReplyRequest) SetRequestID(requestID string) {
	q.RequestID = requestID
	q.require(questionReplyRequestFieldRequestID)
}

// SetDirectory sets the Directory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionReplyRequest) SetDirectory(directory *string) {
	q.Directory = directory
	q.require(questionReplyRequestFieldDirectory)
}

// SetWorkspace sets the Workspace field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionReplyRequest) SetWorkspace(workspace *string) {
	q.Workspace = workspace
	q.require(questionReplyRequestFieldWorkspace)
}

// SetAnswers sets the Answers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuestionReplyRequest) SetAnswers(answers []QuestionAnswer) {
	q.Answers = answers
	q.require(questionReplyRequestFieldAnswers)
}

func (q *QuestionReplyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler QuestionReplyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*q = QuestionReplyRequest(body)
	return nil
}

func (q *QuestionReplyRequest) MarshalJSON() ([]byte, error) {
	type embed QuestionReplyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}
