// Code generated by Fern. DO NOT EDIT.

package project

import (
	context "context"

	sdk "github.com/acksell/opencode-go-sdk/sdk"
	core "github.com/acksell/opencode-go-sdk/sdk/core"
	internal "github.com/acksell/opencode-go-sdk/sdk/internal"
	option "github.com/acksell/opencode-go-sdk/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get a list of projects that have been opened with OpenCode.
func (c *Client) List(
	ctx context.Context,
	request *sdk.ProjectListRequest,
	opts ...option.RequestOption,
) ([]*sdk.Project, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the currently active project that OpenCode is working with.
func (c *Client) Current(
	ctx context.Context,
	request *sdk.ProjectCurrentRequest,
	opts ...option.RequestOption,
) (*sdk.Project, error) {
	response, err := c.WithRawResponse.Current(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a git repository for the current project and return the refreshed project info.
func (c *Client) Initgit(
	ctx context.Context,
	request *sdk.ProjectInitGitRequest,
	opts ...option.RequestOption,
) (*sdk.Project, error) {
	response, err := c.WithRawResponse.Initgit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update project properties such as name, icon, and commands.
func (c *Client) Update(
	ctx context.Context,
	request *sdk.ProjectUpdateRequest,
	opts ...option.RequestOption,
) (*sdk.Project, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
