// Code generated by Fern. DO NOT EDIT.

package permission

import (
	context "context"

	sdk "github.com/Acksell/opencode-go-sdk/sdk"
	core "github.com/Acksell/opencode-go-sdk/sdk/core"
	internal "github.com/Acksell/opencode-go-sdk/sdk/internal"
	option "github.com/Acksell/opencode-go-sdk/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get all pending permission requests across all sessions.
func (c *Client) List(
	ctx context.Context,
	request *sdk.PermissionListRequest,
	opts ...option.RequestOption,
) ([]*sdk.PermissionRequest, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Approve or deny a permission request from the AI assistant.
func (c *Client) Reply(
	ctx context.Context,
	request *sdk.PermissionReplyRequest,
	opts ...option.RequestOption,
) (bool, error) {
	response, err := c.WithRawResponse.Reply(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return false, err
	}
	return response.Body, nil
}
