// Code generated by Fern. DO NOT EDIT.

package client

import (
	config "github.com/acksell/opencode-go-sdk/sdk/config"
	control "github.com/acksell/opencode-go-sdk/sdk/control"
	core "github.com/acksell/opencode-go-sdk/sdk/core"
	global "github.com/acksell/opencode-go-sdk/sdk/global"
	instance "github.com/acksell/opencode-go-sdk/sdk/instance"
	internal "github.com/acksell/opencode-go-sdk/sdk/internal"
	option "github.com/acksell/opencode-go-sdk/sdk/option"
	permission "github.com/acksell/opencode-go-sdk/sdk/permission"
	project "github.com/acksell/opencode-go-sdk/sdk/project"
	provider "github.com/acksell/opencode-go-sdk/sdk/provider"
	question "github.com/acksell/opencode-go-sdk/sdk/question"
	session "github.com/acksell/opencode-go-sdk/sdk/session"
)

type Client struct {
	Control    *control.Client
	Global     *global.Client
	Config     *config.Client
	Instance   *instance.Client
	Project    *project.Client
	Question   *question.Client
	Permission *permission.Client
	Provider   *provider.Client
	Session    *session.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Control:    control.NewClient(options),
		Global:     global.NewClient(options),
		Config:     config.NewClient(options),
		Instance:   instance.NewClient(options),
		Project:    project.NewClient(options),
		Question:   question.NewClient(options),
		Permission: permission.NewClient(options),
		Provider:   provider.NewClient(options),
		Session:    session.NewClient(options),
		options:    options,
		baseURL:    options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
